export default [
  {
    key: 2,
    id: 'name',
    label: 'Name',
    type: 'text',
    value: 'name',
    defaultValue: '',
    errorText: 'Please enter your name',
    element: 'input',
  },
  {
    key: 3,
    id: 'email',
    label: 'Email',
    type: 'email',
    value: 'email',
    defaultValue: '',
    errorText: 'Please enter your email address',
    element: 'input',
  },
  {
    key: 4,
    id: 'subjectLine',
    label: 'Subject Line',
    type: 'text',
    value: 'subjectLine',
    defaultValue: '',
    errorText: 'Please enter a subject line',
    element: 'input',
  },
  {
    key: 5,
    id: 'message',
    label: 'Message',
    type: 'max',
    value: 'message',
    defaultValue: '',
    errorText: 'Please enter a message',
    element: 'textarea',
  },
];
