export default [
  {
    key: 2,
    id: 'name',
    name: 'inquirer_name',
    label: 'Name',
    type: 'text',
    value: 'name',
    defaultValue: '',
    errorText: 'Please enter your name',
    element: 'input',
  },
  {
    key: 3,
    id: 'email',
    name: 'inquirer_email',
    label: 'Email',
    type: 'email',
    value: 'email',
    defaultValue: '',
    errorText: 'Please enter your email address',
    element: 'input',
  },
  {
    key: 4,
    id: 'subjectLine',
    name: 'inquiry_subject_line',
    label: 'Subject Line',
    type: 'text',
    value: 'subjectLine',
    defaultValue: '',
    errorText: 'Please enter a subject line',
    element: 'input',
  },
  {
    key: 5,
    id: 'message',
    name: 'inquiry_message',
    label: 'Message (Maximum 200 characters)',
    type: 'max--text',
    value: 'message',
    defaultValue: '',
    errorText: 'Please enter a message within 200 characters',
    element: 'textarea',
  },
];
