export const games = [
  {
    _id: 'g1',
    name: 'Kentucky Route Zero',
    developer: '343 Industries',
    publisher: 'Bandai Namco',
    releaseDate: '2022-09-29T04:00:00.000+00:00',
    genre: 'Simulation',
    platform: 'Nintendo Switch',
    tag: 'adventure',
    __v: 0,
  },
  {
    _id: 'g2',
    name: 'Guild Wars 2',
    developer: 'Square Enix',
    publisher: 'Activision',
    releaseDate: '2023-04-11T04:00:00.000+00:00',
    genre: 'Sports',
    platform: 'PlayStation 4',
    tag: 'role-playing',
    __v: 0,
  },
  {
    _id: 'g3',
    name: 'Hades',
    developer: 'CD Projekt Red',
    publisher: 'Capcom',
    releaseDate: '2022-12-04T05:00:00.000+00:00',
    genre: 'Fighting',
    platform: 'PlayStation 4',
    tag: 'action',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075c6',
    name: 'Destiny 2',
    developer: 'Microsoft Studios',
    publisher: 'Electronic Arts',
    releaseDate: '2022-06-18T04:00:00.000+00:00',
    genre: 'Shooter',
    platform: 'Xbox One',
    tag: 'action',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075c5',
    name: 'The Stanley Parable',
    developer: 'Namco',
    publisher: 'Ubisoft',
    releaseDate: '2023-01-17T05:00:00.000+00:00',
    genre: 'Strategy',
    platform: 'Nintendo Switch',
    tag: 'shooter',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075ca',
    name: 'Crusader Kings III',
    developer: 'Blizzard Entertainment',
    publisher: 'Konami',
    releaseDate: '2022-12-01T05:00:00.000+00:00',
    genre: 'Platformer',
    platform: 'PlayStation 4',
    tag: 'action',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075c7',
    name: 'Until Dawn',
    developer: 'Electronic Arts',
    publisher: 'Take-Two Interactive',
    releaseDate: '2023-03-24T04:00:00.000+00:00',
    genre: 'RPG',
    platform: 'Nintendo Switch',
    tag: 'strategy',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075c8',
    name: 'Age of Empires II',
    developer: 'Rockstar Games',
    publisher: 'THQ Nordic',
    releaseDate: '2023-06-06T04:00:00.000+00:00',
    genre: 'Sports',
    platform: 'PlayStation 4',
    tag: 'action',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075cc',
    name: 'Middle-earth: Shadow of Mordor',
    developer: 'Capcom',
    publisher: 'THQ Nordic',
    releaseDate: '2022-08-01T04:00:00.000+00:00',
    genre: 'Strategy',
    platform: 'PlayStation 4',
    tag: 'platformer',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075cb',
    name: 'Paper Mario: The Origami King',
    developer: 'Gearbox Software',
    publisher: 'Devolver Digital',
    releaseDate: '2023-03-12T05:00:00.000+00:00',
    genre: 'Sports',
    platform: 'PlayStation 4',
    tag: 'role-playing',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075cd',
    name: 'Hollow Knight',
    developer: 'Activision',
    publisher: 'Square Enix',
    releaseDate: '2023-01-27T05:00:00.000+00:00',
    genre: 'Shooter',
    platform: 'Nintendo Switch',
    tag: 'racing',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075ce',
    name: 'Xenoblade Chronicles 2',
    developer: 'Konami',
    publisher: 'Valve Corporation',
    releaseDate: '2022-09-11T04:00:00.000+00:00',
    genre: 'Simulation',
    platform: 'Xbox One',
    tag: 'shooter',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075cf',
    name: "Pokémon: Let's Go",
    developer: 'CD Projekt Red',
    publisher: 'Activision',
    releaseDate: '2023-06-08T04:00:00.000+00:00',
    genre: 'Adventure',
    platform: 'PlayStation 4',
    tag: 'adventure',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075d0',
    name: 'The Vanishing of Ethan Carter',
    developer: 'Microsoft Studios',
    publisher: 'Microsoft Studios',
    releaseDate: '2022-11-02T04:00:00.000+00:00',
    genre: 'Fighting',
    platform: 'Xbox One',
    tag: 'simulation',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075d1',
    name: 'Machinarium',
    developer: 'Namco',
    publisher: 'Electronic Arts',
    releaseDate: '2023-01-16T05:00:00.000+00:00',
    genre: 'Sports',
    platform: 'Xbox One',
    tag: 'simulation',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075d2',
    name: 'Batman: Arkham City',
    developer: 'Bethesda Softworks',
    publisher: 'Nintendo',
    releaseDate: '2022-09-29T04:00:00.000+00:00',
    genre: 'Adventure',
    platform: 'Nintendo Switch',
    tag: 'action',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075d3',
    name: 'BioShock Infinite',
    developer: 'Konami',
    publisher: 'Valve Corporation',
    releaseDate: '2022-12-29T05:00:00.000+00:00',
    genre: 'Shooter',
    platform: 'PlayStation 4',
    tag: 'adventure',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075d5',
    name: 'Everquest',
    developer: 'Valve Corporation',
    publisher: 'Nintendo',
    releaseDate: '2022-11-15T05:00:00.000+00:00',
    genre: 'Strategy',
    platform: 'Xbox One',
    tag: 'platformer',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075d6',
    name: 'Sekiro: Shadows Die Twice',
    developer: 'Epic Games',
    publisher: '2K Games',
    releaseDate: '2023-03-27T04:00:00.000+00:00',
    genre: 'Platformer',
    platform: 'PlayStation 4',
    tag: 'strategy',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075d4',
    name: 'Resident Evil 3',
    developer: 'Bethesda Softworks',
    publisher: 'Sega',
    releaseDate: '2022-10-03T04:00:00.000+00:00',
    genre: 'Platformer',
    platform: 'Nintendo Switch',
    tag: 'strategy',
    __v: 0,
  },
];

export const users = [
  {
    _id: 'u1',
    userName: 'bdearden0',
    email: 'aflynn0@bluehost.com',
    password: '$2a$04$a4179HhWb9fEdIPEvEAW.uVBcdPCHHoRq7X0.HD0kd/Mwbl3losaS',
    isAdmin: true,
    avatar: 'https://robohash.org/etimpeditcorporis.png?size=50x50&set=set1',
    status: 'active',
    favouriteGame: 'Overwatch',
    wishList: 'Overwatch',
    channelURL: 'https://www.youtube.com/channel/cIhS_K-SE--',
    joinedAffiliation: true,
    __v: { $numberInt: '0' },
  },
  {
    _id: 'u2',
    userName: 'mwinscom3',
    email: 'equinnet3@unblog.fr',
    password: '$2a$04$VqQtMHF5No4bSgywcuaiZOd9PgYECyc1//HX9KfbNJZINgFnoob1q',
    isAdmin: false,
    avatar: 'https://robohash.org/nisiiustoomnis.png?size=50x50&set=set1',
    status: 'suspended',
    favouriteGame: 'FIFA 21',
    wishList: 'FIFA 21',
    channelURL: 'http://www.youtube.com/channel/n3--B-_5-__',
    joinedAffiliation: false,
    __v: { $numberInt: '0' },
  },
  {
    _id: 'u3',
    userName: 'gesel4',
    email: 'rsherborne4@tamu.edu',
    password: '$2a$04$HDVcNO4pg3zKapE7iSZms.gEPBG4i.Tdnrft5zsn54iilXGVDLN/m',
    isAdmin: false,
    avatar: 'https://robohash.org/voluptateautquis.png?size=50x50&set=set1',
    status: 'active',
    favouriteGame: 'Overwatch',
    wishList: 'Minecraft',
    channelURL: 'http://www.youtube.com/channel/-_GwP35-5_-',
    joinedAffiliation: true,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb074ff' },
    userName: 'vkenny5',
    email: 'gaird5@netvibes.com',
    password: '$2a$04$9IcZGmG7Tld4CgrFbrxm.ONn1n76BtVN/Z8uwcMhzKAXZCIKibLg2',
    isAdmin: false,
    avatar: 'https://robohash.org/suntsequilibero.png?size=50x50&set=set1',
    status: 'active',
    favouriteGame: 'Overwatch',
    wishList: 'FIFA 21',
    channelURL: 'https://www.youtube.com/channel/VATs_45_--3',
    joinedAffiliation: false,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb07501' },
    userName: 'sghelardoni7',
    email: 'alisimore7@slideshare.net',
    password: '$2a$04$vg..ufgtDQk/p1CPCuy3TOGy.3KW.uejynY09qXCgmkHK0A5IyA6S',
    isAdmin: false,
    avatar: 'https://robohash.org/possimusmagnilaudantium.png?size=50x50&set=set1',
    status: 'suspended',
    favouriteGame: 'The Legend of Zelda',
    wishList: 'Call of Duty: Modern Warfare',
    channelURL: 'https://www.youtube.com/channel/__XDgU4_-CH',
    joinedAffiliation: true,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb07500' },
    userName: 'clording6',
    email: 'aornils6@comsenz.com',
    password: '$2a$04$1MHGEcjVUoSysghgz.AEKuBq03o.eKLE..o6zEtV.hlWIrNgolTMK',
    isAdmin: false,
    avatar: 'https://robohash.org/earumsunteius.png?size=50x50&set=set1',
    status: 'suspended',
    favouriteGame: 'Minecraft',
    wishList: 'Red Dead Redemption 2',
    channelURL: 'http://www.youtube.com/channel/qyYOIyM7__T',
    joinedAffiliation: true,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb07502' },
    userName: 'alemmanbie8',
    email: 'bbullerwell8@comsenz.com',
    password: '$2a$04$McpSDHQgY3sNLOiUjoDx2OJpsUDhHNAqFedCiMP3ke.F3zeV7/jA.',
    isAdmin: false,
    avatar: 'https://robohash.org/nonreiciendisin.png?size=50x50&set=set1',
    status: 'suspended',
    favouriteGame: 'Fortnite',
    wishList: 'Overwatch',
    channelURL: 'https://www.youtube.com/channel/76DB-dsC3Z_',
    joinedAffiliation: true,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb07503' },
    userName: 'mgillion9',
    email: 'elillo9@cloudflare.com',
    password: '$2a$04$zpF3jwsGFOFO3fChBURdfuy4p7TrHuCGSPlvODMRCm14aXsqXRnUu',
    isAdmin: false,
    avatar: 'https://robohash.org/ipsumquisquamcumque.png?size=50x50&set=set1',
    status: 'active',
    favouriteGame: null,
    wishList: null,
    channelURL: 'https://www.youtube.com/channel/3wj-2--bSa3',
    joinedAffiliation: true,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb07504' },
    userName: 'awardalla',
    email: 'amcgunleya@a8.net',
    password: '$2a$04$JIF9GKB32LtIcn0M9pV9.OGN5uvbdqSAXHmeyiT4qgCpsBlxuWJim',
    isAdmin: false,
    avatar: 'https://robohash.org/temporibussuntplaceat.png?size=50x50&set=set1',
    status: 'banned',
    favouriteGame: 'Super Mario Bros.',
    wishList: 'Overwatch',
    channelURL: 'http://www.youtube.com/channel/uvsgj_KLY_4',
    joinedAffiliation: false,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb074fb' },
    userName: 'tspears1',
    email: 'dber1@rediff.com',
    password: '$2a$04$8yDrblHU.t4.BKmr8KcUZ.SbYW0.jjO69rKhzbfhmvyfqZgqorFAu',
    isAdmin: false,
    avatar: 'https://robohash.org/inquiamagni.png?size=50x50&set=set1',
    status: 'active',
    favouriteGame: 'Call of Duty: Modern Warfare',
    wishList: 'Super Mario Bros.',
    channelURL: 'http://www.youtube.com/channel/5ny1mG8YFkE',
    joinedAffiliation: false,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb074fc' },
    userName: 'dbezarra2',
    email: 'sblaw2@independent.co.uk',
    password: '$2a$04$spxij48EDbDZ5lj9gmt39elj0T.JXxAVIFyz/ciiP10sZE/uQ8N02',
    isAdmin: false,
    avatar: 'https://robohash.org/adetsit.png?size=50x50&set=set1',
    status: 'active',
    favouriteGame: "Assassin's Creed Valhalla",
    wishList: "Assassin's Creed Valhalla",
    channelURL: 'http://www.youtube.com/channel/-zF6__D3o-_',
    joinedAffiliation: true,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb07507' },
    userName: 'brhucroftd',
    email: 'vlongead@imgur.com',
    password: '$2a$04$62j8VG4yivQdOapYl1kKS.b2OfqRxfVZ2rqmxoU0uFNSzbwStQnzu',
    isAdmin: false,
    avatar: 'https://robohash.org/errorsimiliquesed.png?size=50x50&set=set1',
    status: 'suspended',
    favouriteGame: 'FIFA 21',
    wishList: 'Call of Duty: Modern Warfare',
    channelURL: 'https://www.youtube.com/channel/Qw_-05-0649',
    joinedAffiliation: false,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb07508' },
    userName: 'omateeve',
    email: 'omcphersone@cmu.edu',
    password: '$2a$04$EsWnWyb5wnvu4ptYLSXNkeVMk1aHb/drDApycpaSii397H72mqy/u',
    isAdmin: false,
    avatar: 'https://robohash.org/veritatispossimussoluta.png?size=50x50&set=set1',
    status: 'active',
    favouriteGame: 'The Legend of Zelda',
    wishList: 'Grand Theft Auto V',
    channelURL: 'https://www.youtube.com/channel/r-1-_C_b-C1',
    joinedAffiliation: true,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb07509' },
    userName: 'dwalwoodf',
    email: 'gslinef@pen.io',
    password: '$2a$04$za1ANS5IXBHWPSSI6o01j.lhEL15ITEuQksgJRmJ2eDLpe2XG4qHi',
    isAdmin: false,
    avatar: 'https://robohash.org/voluptatemutmagni.png?size=50x50&set=set1',
    status: 'active',
    favouriteGame: 'The Legend of Zelda',
    wishList: 'Fortnite',
    channelURL: 'https://www.youtube.com/channel/u-_a36pqH_Q',
    joinedAffiliation: false,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb0750a' },
    userName: 'challgalleyg',
    email: 'mmcleseg@discovery.com',
    password: '$2a$04$vVqKmRFnhLB/Z7cYKLLmA.YFe7MqJA27Gzhma/k9EkXOa5VUjeWGa',
    isAdmin: false,
    avatar: 'https://robohash.org/rerumearumnihil.png?size=50x50&set=set1',
    status: 'active',
    favouriteGame: 'Red Dead Redemption 2',
    wishList: 'The Legend of Zelda',
    channelURL: 'https://www.youtube.com/channel/-PO-_-_1-W_',
    joinedAffiliation: false,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb0750d' },
    userName: 'cblazhevichj',
    email: 'alormanj@storify.com',
    password: '$2a$04$Fs7TRkboOfrT8ooM./ALK.qr0uMgnKiNMwZJwTESVp3FvY1ZWciKa',
    isAdmin: false,
    avatar: 'https://robohash.org/repudiandaemolestiaevel.png?size=50x50&set=set1',
    status: 'active',
    favouriteGame: 'FIFA 21',
    wishList: 'The Legend of Zelda',
    channelURL: 'https://www.youtube.com/channel/-98_-_2-an_',
    joinedAffiliation: false,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb0750e' },
    userName: 'dcleyburnk',
    email: 'vdaubneyk@histats.com',
    password: '$2a$04$KyadSvC2Pfisnfagh3cE3Os7fz5qy5w7nO.4owQsKn9Vvgutq5c1u',
    isAdmin: false,
    avatar: 'https://robohash.org/quietmolestiae.png?size=50x50&set=set1',
    status: 'active',
    favouriteGame: 'Super Mario Bros.',
    wishList: 'Minecraft',
    channelURL: 'https://www.youtube.com/channel/__6__2qOxxz',
    joinedAffiliation: true,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb0750b' },
    userName: 'divanyushinh',
    email: 'imackayh@angelfire.com',
    password: '$2a$04$1kOCw.qWCwwyVu9hAcItk.77fc5idbbcPR.ZR/ILBdrZYJMC7B4O6',
    isAdmin: false,
    avatar: 'https://robohash.org/iustoeaquia.png?size=50x50&set=set1',
    status: 'active',
    favouriteGame: 'Overwatch',
    wishList: 'FIFA 21',
    channelURL: 'http://www.youtube.com/channel/--9_-Ir0fUB',
    joinedAffiliation: false,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb0750c' },
    userName: 'vdeami',
    email: 'hlomasneyi@vimeo.com',
    password: '$2a$04$zRg7GYtzG5rDtYR4ktGTWu6aotJhShUFC6DuK7c/VtrcV4B0hZWA2',
    isAdmin: false,
    avatar: 'https://robohash.org/inventorequamearum.png?size=50x50&set=set1',
    status: 'active',
    favouriteGame: 'Super Mario Bros.',
    wishList: 'FIFA 21',
    channelURL: 'http://www.youtube.com/channel/5-3V_EFk8_c',
    joinedAffiliation: false,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb0750f' },
    userName: 'dmaffullil',
    email: 'eduttonl@tumblr.com',
    password: '$2a$04$5IH/sIZbfmiYedFMilugnuyV1Lyw69YIZLViJS4J.fbX38c6k5LQy',
    isAdmin: false,
    avatar: 'https://robohash.org/minimaetdolore.png?size=50x50&set=set1',
    status: 'active',
    favouriteGame: 'Minecraft',
    wishList: 'Overwatch',
    channelURL: 'https://www.youtube.com/channel/__D-__5B5_k',
    joinedAffiliation: false,
    __v: { $numberInt: '0' },
  },
];

export const reviews = [
  {
    _id: 'r1',
    userId: '5805',
    gameId: '6812',
    rating: '55',
    title: 'A Great Multiplayer Experience',
    content:
      'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',
    postDate: '1670821200000',
    comments: [
      {
        commentId: 'c1',
        commentUserId: 'u1',
        comment:
          'In congue. Etiam justo. Etiam pretium iaculis justo.\n\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.',
        commentReportCount: '0',
        status: 'active',
        reports: [
          {
            reportID: '6585',
            reportUserID: 'u1',
            report:
              'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.',
          },
        ],
      },
    ],
    reviewReportCount: '1',
    reviewStatus: 'active',
    reports: [
      {
        reportId: '898',
        report_userId: 'u1',
        report: 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.',
      },
    ],
    __v: '0',
  },
  {
    _id: 'r2',
    userId: '1248',
    gameId: '2796',
    rating: '80',
    title: 'Addictive Gameplay',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed cursus, turpis in congue feugiat, velit nisi convallis urna, vitae iaculis massa mauris sed lectus. In rhoncus fermentum tortor, sit amet placerat urna fringilla eu. Proin auctor libero vitae magna volutpat lobortis. Donec pretium semper metus, ut aliquam velit consequat eget. Sed vel felis id justo posuere efficitur. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla vitae facilisis elit. Mauris accumsan orci vel risus malesuada, sed laoreet justo posuere.',
    postDate: '1698056400000',
    comments: [
      {
        commentId: 'c2',
        commentUserId: 'u2',
        comment:
          'Ut egestas, nisi id lacinia sollicitudin, lorem neque ultricies risus, eu scelerisque mi orci non nulla. Phasellus vitae leo a est tincidunt lacinia. Sed vitae nisl vitae ante vulputate sollicitudin.',
        commentReportCount: '2',
        status: 'active',
        reports: [
          {
            reportID: '2457',
            reportUserID: '725',
            report:
              'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam iaculis dolor sed dui semper iaculis.',
          },
          {
            reportID: '3568',
            reportUserID: '953',
            report: 'Proin lobortis nulla ac fermentum tincidunt.',
          },
        ],
      },
      {
        commentId: 'c3',
        commentUserId: 'u3',
        comment:
          'Suspendisse lobortis leo non sapien rhoncus, ut placerat nulla facilisis. Integer vehicula urna id luctus pulvinar. Integer ut vestibulum erat, a dictum neque. Nullam ac facilisis lacus.',
        commentReportCount: '0',
        status: 'active',
        reports: [],
      },
    ],
    reviewReportCount: '0',
    reviewStatus: 'active',
    reports: [],
    __v: '0',
  },
  {
    _id: 'r3',
    userId: '9876',
    gameId: '5432',
    rating: '90',
    title: 'Immersive Storyline',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed mattis lobortis cursus. Morbi vitae tellus quis felis gravida congue. Duis auctor tortor lacus, eu congue velit posuere ac. Donec malesuada, nisi in rhoncus finibus, sem justo egestas tortor, non mattis dolor lectus vel velit. Fusce ac risus et nunc consectetur pharetra vel in ligula. Integer a lectus dapibus, tempor lorem ut, sagittis velit. Sed vestibulum pharetra justo sed accumsan. Nam nec lorem mauris. Proin tincidunt purus leo, ac fermentum odio cursus in. Nulla malesuada justo et neque tincidunt pulvinar. Nam semper aliquet turpis. Cras pretium feugiat odio.',
    postDate: '1724542800000',
    comments: [
      {
        commentId: '7',
        commentUserId: '205',
        comment:
          'Aliquam erat volutpat. Sed vel cursus arcu. Suspendisse a nunc sed elit hendrerit feugiat id vitae lorem.',
        commentReportCount: '1',
        status: 'active',
        reports: [
          {
            reportID: '9872',
            reportUserID: '409',
            report: 'Maecenas eu metus eget urna convallis rutrum non at erat.',
          },
        ],
      },
      {
        commentId: '15',
        commentUserId: '712',
        comment:
          'Phasellus gravida aliquet ipsum, vel dapibus dolor congue vitae. Nullam eleifend eu leo vel tristique. Nullam tristique, erat in rhoncus efficitur, est massa congue nulla, ac iaculis ex mauris vitae sapien.',
        commentReportCount: '0',
        status: 'active',
        reports: [],
      },
    ],
    reviewReportCount: '2',
    reviewStatus: 'active',
    reports: [
      {
        reportId: '763',
        report_userId: 'u2',
        report: 'Nunc lacinia consequat magna, id efficitur lacus aliquam a.',
      },
      {
        reportId: '897',
        report_userId: 'u1',
        report: 'Curabitur sed ipsum ullamcorper, pharetra sem vitae, tincidunt metus.',
      },
    ],
    __v: '0',
  },
  {
    _id: { $oid: 'f6d5e4c3b2a1' },
    userId: '2468',
    gameId: '1357',
    rating: '75',
    title: 'Challenging Gameplay',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut feugiat justo a interdum elementum. Vestibulum id posuere velit, vitae efficitur lacus. Integer gravida mauris et tristique sollicitudin. Quisque vel elit at dolor consequat accumsan. Proin tristique laoreet tristique. Morbi vitae purus purus. Suspendisse bibendum aliquet nunc, vel consectetur ante facilisis eu.',
    postDate: '1746354000000',
    comments: [
      {
        commentId: '9',
        commentUserId: '824',
        comment:
          'Vivamus congue metus quis sapien auctor consectetur. Cras finibus scelerisque felis, ut finibus enim volutpat nec. Duis ac neque vel risus tristique pellentesque vitae et lectus.',
        commentReportCount: '0',
        status: 'active',
        reports: [],
      },
      {
        commentId: '22',
        commentUserId: '976',
        comment:
          'Praesent eget orci interdum, gravida mi eu, tempus elit. Ut a scelerisque nunc. Nullam facilisis, risus id aliquam tristique, leo augue hendrerit nunc, at fermentum augue neque auctor tellus.',
        commentReportCount: '3',
        status: 'active',
        reports: [
          {
            reportID: '5671',
            reportUserID: '685',
            report:
              'Nam vehicula, est non sagittis lacinia, ante nunc malesuada ex, id auctor justo mi id purus.',
          },
          {
            reportID: '6782',
            reportUserID: '993',
            report:
              'Proin tincidunt, metus vel efficitur lacinia, elit lectus posuere ante, nec lobortis dolor magna vel risus.',
          },
          {
            reportID: '7893',
            reportUserID: '117',
            report: 'Sed eu ex vitae felis gravida vulputate id a est.',
          },
        ],
      },
    ],
    reviewReportCount: '1',
    reviewStatus: 'active',
    reports: [
      {
        reportId: '234',
        report_userId: 'u3',
        report: 'Sed eu risus eu metus iaculis pharetra nec at nisl.',
      },
    ],
    __v: '0',
  },
];
