export const games = [
  {
    _id: '648fb8ce2a35a03f1bb075c2',
    name: 'Kentucky Route Zero',
    developer: '343 Industries',
    publisher: 'Bandai Namco',
    releaseDate: '2022-09-29T04:00:00.000+00:00',
    genre: 'Simulation',
    platform: 'Nintendo Switch',
    tag: 'adventure',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075c4',
    name: 'Guild Wars 2',
    developer: 'Square Enix',
    publisher: 'Activision',
    releaseDate: '2023-04-11T04:00:00.000+00:00',
    genre: 'Sports',
    platform: 'PlayStation 4',
    tag: 'role-playing',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075c9',
    name: 'Hades',
    developer: 'CD Projekt Red',
    publisher: 'Capcom',
    releaseDate: '2022-12-04T05:00:00.000+00:00',
    genre: 'Fighting',
    platform: 'PlayStation 4',
    tag: 'action',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075c6',
    name: 'Destiny 2',
    developer: 'Microsoft Studios',
    publisher: 'Electronic Arts',
    releaseDate: '2022-06-18T04:00:00.000+00:00',
    genre: 'Shooter',
    platform: 'Xbox One',
    tag: 'action',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075c5',
    name: 'The Stanley Parable',
    developer: 'Namco',
    publisher: 'Ubisoft',
    releaseDate: '2023-01-17T05:00:00.000+00:00',
    genre: 'Strategy',
    platform: 'Nintendo Switch',
    tag: 'shooter',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075ca',
    name: 'Crusader Kings III',
    developer: 'Blizzard Entertainment',
    publisher: 'Konami',
    releaseDate: '2022-12-01T05:00:00.000+00:00',
    genre: 'Platformer',
    platform: 'PlayStation 4',
    tag: 'action',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075c7',
    name: 'Until Dawn',
    developer: 'Electronic Arts',
    publisher: 'Take-Two Interactive',
    releaseDate: '2023-03-24T04:00:00.000+00:00',
    genre: 'RPG',
    platform: 'Nintendo Switch',
    tag: 'strategy',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075c8',
    name: 'Age of Empires II',
    developer: 'Rockstar Games',
    publisher: 'THQ Nordic',
    releaseDate: '2023-06-06T04:00:00.000+00:00',
    genre: 'Sports',
    platform: 'PlayStation 4',
    tag: 'action',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075cc',
    name: 'Middle-earth: Shadow of Mordor',
    developer: 'Capcom',
    publisher: 'THQ Nordic',
    releaseDate: '2022-08-01T04:00:00.000+00:00',
    genre: 'Strategy',
    platform: 'PlayStation 4',
    tag: 'platformer',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075cb',
    name: 'Paper Mario: The Origami King',
    developer: 'Gearbox Software',
    publisher: 'Devolver Digital',
    releaseDate: '2023-03-12T05:00:00.000+00:00',
    genre: 'Sports',
    platform: 'PlayStation 4',
    tag: 'role-playing',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075cd',
    name: 'Hollow Knight',
    developer: 'Activision',
    publisher: 'Square Enix',
    releaseDate: '2023-01-27T05:00:00.000+00:00',
    genre: 'Shooter',
    platform: 'Nintendo Switch',
    tag: 'racing',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075ce',
    name: 'Xenoblade Chronicles 2',
    developer: 'Konami',
    publisher: 'Valve Corporation',
    releaseDate: '2022-09-11T04:00:00.000+00:00',
    genre: 'Simulation',
    platform: 'Xbox One',
    tag: 'shooter',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075cf',
    name: "Pokémon: Let's Go",
    developer: 'CD Projekt Red',
    publisher: 'Activision',
    releaseDate: '2023-06-08T04:00:00.000+00:00',
    genre: 'Adventure',
    platform: 'PlayStation 4',
    tag: 'adventure',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075d0',
    name: 'The Vanishing of Ethan Carter',
    developer: 'Microsoft Studios',
    publisher: 'Microsoft Studios',
    releaseDate: '2022-11-02T04:00:00.000+00:00',
    genre: 'Fighting',
    platform: 'Xbox One',
    tag: 'simulation',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075d1',
    name: 'Machinarium',
    developer: 'Namco',
    publisher: 'Electronic Arts',
    releaseDate: '2023-01-16T05:00:00.000+00:00',
    genre: 'Sports',
    platform: 'Xbox One',
    tag: 'simulation',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075d2',
    name: 'Batman: Arkham City',
    developer: 'Bethesda Softworks',
    publisher: 'Nintendo',
    releaseDate: '2022-09-29T04:00:00.000+00:00',
    genre: 'Adventure',
    platform: 'Nintendo Switch',
    tag: 'action',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075d3',
    name: 'BioShock Infinite',
    developer: 'Konami',
    publisher: 'Valve Corporation',
    releaseDate: '2022-12-29T05:00:00.000+00:00',
    genre: 'Shooter',
    platform: 'PlayStation 4',
    tag: 'adventure',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075d5',
    name: 'Everquest',
    developer: 'Valve Corporation',
    publisher: 'Nintendo',
    releaseDate: '2022-11-15T05:00:00.000+00:00',
    genre: 'Strategy',
    platform: 'Xbox One',
    tag: 'platformer',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075d6',
    name: 'Sekiro: Shadows Die Twice',
    developer: 'Epic Games',
    publisher: '2K Games',
    releaseDate: '2023-03-27T04:00:00.000+00:00',
    genre: 'Platformer',
    platform: 'PlayStation 4',
    tag: 'strategy',
    __v: 0,
  },
  {
    _id: '648fb8ce2a35a03f1bb075d4',
    name: 'Resident Evil 3',
    developer: 'Bethesda Softworks',
    publisher: 'Sega',
    releaseDate: '2022-10-03T04:00:00.000+00:00',
    genre: 'Platformer',
    platform: 'Nintendo Switch',
    tag: 'strategy',
    __v: 0,
  },
];

export const users = [
  {
    _id: { $oid: '648fb8ce2a35a03f1bb074fa' },
    userName: 'bdearden0',
    email: 'aflynn0@bluehost.com',
    password: '$2a$04$a4179HhWb9fEdIPEvEAW.uVBcdPCHHoRq7X0.HD0kd/Mwbl3losaS',
    isAdmin: true,
    avatar: 'https://robohash.org/etimpeditcorporis.png?size=50x50&set=set1',
    status: 'active',
    favouriteGame: 'Overwatch',
    wishList: 'Overwatch',
    channelURL: 'https://www.youtube.com/channel/cIhS_K-SE--',
    joinedAffiliation: true,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb074fd' },
    userName: 'mwinscom3',
    email: 'equinnet3@unblog.fr',
    password: '$2a$04$VqQtMHF5No4bSgywcuaiZOd9PgYECyc1//HX9KfbNJZINgFnoob1q',
    isAdmin: false,
    avatar: 'https://robohash.org/nisiiustoomnis.png?size=50x50&set=set1',
    status: 'suspended',
    favouriteGame: 'FIFA 21',
    wishList: 'FIFA 21',
    channelURL: 'http://www.youtube.com/channel/n3--B-_5-__',
    joinedAffiliation: false,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb074fe' },
    userName: 'gesel4',
    email: 'rsherborne4@tamu.edu',
    password: '$2a$04$HDVcNO4pg3zKapE7iSZms.gEPBG4i.Tdnrft5zsn54iilXGVDLN/m',
    isAdmin: false,
    avatar: 'https://robohash.org/voluptateautquis.png?size=50x50&set=set1',
    status: 'active',
    favouriteGame: 'Overwatch',
    wishList: 'Minecraft',
    channelURL: 'http://www.youtube.com/channel/-_GwP35-5_-',
    joinedAffiliation: true,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb074ff' },
    userName: 'vkenny5',
    email: 'gaird5@netvibes.com',
    password: '$2a$04$9IcZGmG7Tld4CgrFbrxm.ONn1n76BtVN/Z8uwcMhzKAXZCIKibLg2',
    isAdmin: false,
    avatar: 'https://robohash.org/suntsequilibero.png?size=50x50&set=set1',
    status: 'active',
    favouriteGame: 'Overwatch',
    wishList: 'FIFA 21',
    channelURL: 'https://www.youtube.com/channel/VATs_45_--3',
    joinedAffiliation: false,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb07501' },
    userName: 'sghelardoni7',
    email: 'alisimore7@slideshare.net',
    password: '$2a$04$vg..ufgtDQk/p1CPCuy3TOGy.3KW.uejynY09qXCgmkHK0A5IyA6S',
    isAdmin: false,
    avatar: 'https://robohash.org/possimusmagnilaudantium.png?size=50x50&set=set1',
    status: 'suspended',
    favouriteGame: 'The Legend of Zelda',
    wishList: 'Call of Duty: Modern Warfare',
    channelURL: 'https://www.youtube.com/channel/__XDgU4_-CH',
    joinedAffiliation: true,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb07500' },
    userName: 'clording6',
    email: 'aornils6@comsenz.com',
    password: '$2a$04$1MHGEcjVUoSysghgz.AEKuBq03o.eKLE..o6zEtV.hlWIrNgolTMK',
    isAdmin: false,
    avatar: 'https://robohash.org/earumsunteius.png?size=50x50&set=set1',
    status: 'suspended',
    favouriteGame: 'Minecraft',
    wishList: 'Red Dead Redemption 2',
    channelURL: 'http://www.youtube.com/channel/qyYOIyM7__T',
    joinedAffiliation: true,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb07502' },
    userName: 'alemmanbie8',
    email: 'bbullerwell8@comsenz.com',
    password: '$2a$04$McpSDHQgY3sNLOiUjoDx2OJpsUDhHNAqFedCiMP3ke.F3zeV7/jA.',
    isAdmin: false,
    avatar: 'https://robohash.org/nonreiciendisin.png?size=50x50&set=set1',
    status: 'suspended',
    favouriteGame: 'Fortnite',
    wishList: 'Overwatch',
    channelURL: 'https://www.youtube.com/channel/76DB-dsC3Z_',
    joinedAffiliation: true,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb07503' },
    userName: 'mgillion9',
    email: 'elillo9@cloudflare.com',
    password: '$2a$04$zpF3jwsGFOFO3fChBURdfuy4p7TrHuCGSPlvODMRCm14aXsqXRnUu',
    isAdmin: false,
    avatar: 'https://robohash.org/ipsumquisquamcumque.png?size=50x50&set=set1',
    status: 'active',
    favouriteGame: null,
    wishList: null,
    channelURL: 'https://www.youtube.com/channel/3wj-2--bSa3',
    joinedAffiliation: true,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb07504' },
    userName: 'awardalla',
    email: 'amcgunleya@a8.net',
    password: '$2a$04$JIF9GKB32LtIcn0M9pV9.OGN5uvbdqSAXHmeyiT4qgCpsBlxuWJim',
    isAdmin: false,
    avatar: 'https://robohash.org/temporibussuntplaceat.png?size=50x50&set=set1',
    status: 'banned',
    favouriteGame: 'Super Mario Bros.',
    wishList: 'Overwatch',
    channelURL: 'http://www.youtube.com/channel/uvsgj_KLY_4',
    joinedAffiliation: false,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb074fb' },
    userName: 'tspears1',
    email: 'dber1@rediff.com',
    password: '$2a$04$8yDrblHU.t4.BKmr8KcUZ.SbYW0.jjO69rKhzbfhmvyfqZgqorFAu',
    isAdmin: false,
    avatar: 'https://robohash.org/inquiamagni.png?size=50x50&set=set1',
    status: 'active',
    favouriteGame: 'Call of Duty: Modern Warfare',
    wishList: 'Super Mario Bros.',
    channelURL: 'http://www.youtube.com/channel/5ny1mG8YFkE',
    joinedAffiliation: false,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb074fc' },
    userName: 'dbezarra2',
    email: 'sblaw2@independent.co.uk',
    password: '$2a$04$spxij48EDbDZ5lj9gmt39elj0T.JXxAVIFyz/ciiP10sZE/uQ8N02',
    isAdmin: false,
    avatar: 'https://robohash.org/adetsit.png?size=50x50&set=set1',
    status: 'active',
    favouriteGame: "Assassin's Creed Valhalla",
    wishList: "Assassin's Creed Valhalla",
    channelURL: 'http://www.youtube.com/channel/-zF6__D3o-_',
    joinedAffiliation: true,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb07507' },
    userName: 'brhucroftd',
    email: 'vlongead@imgur.com',
    password: '$2a$04$62j8VG4yivQdOapYl1kKS.b2OfqRxfVZ2rqmxoU0uFNSzbwStQnzu',
    isAdmin: false,
    avatar: 'https://robohash.org/errorsimiliquesed.png?size=50x50&set=set1',
    status: 'suspended',
    favouriteGame: 'FIFA 21',
    wishList: 'Call of Duty: Modern Warfare',
    channelURL: 'https://www.youtube.com/channel/Qw_-05-0649',
    joinedAffiliation: false,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb07508' },
    userName: 'omateeve',
    email: 'omcphersone@cmu.edu',
    password: '$2a$04$EsWnWyb5wnvu4ptYLSXNkeVMk1aHb/drDApycpaSii397H72mqy/u',
    isAdmin: false,
    avatar: 'https://robohash.org/veritatispossimussoluta.png?size=50x50&set=set1',
    status: 'active',
    favouriteGame: 'The Legend of Zelda',
    wishList: 'Grand Theft Auto V',
    channelURL: 'https://www.youtube.com/channel/r-1-_C_b-C1',
    joinedAffiliation: true,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb07509' },
    userName: 'dwalwoodf',
    email: 'gslinef@pen.io',
    password: '$2a$04$za1ANS5IXBHWPSSI6o01j.lhEL15ITEuQksgJRmJ2eDLpe2XG4qHi',
    isAdmin: false,
    avatar: 'https://robohash.org/voluptatemutmagni.png?size=50x50&set=set1',
    status: 'active',
    favouriteGame: 'The Legend of Zelda',
    wishList: 'Fortnite',
    channelURL: 'https://www.youtube.com/channel/u-_a36pqH_Q',
    joinedAffiliation: false,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb0750a' },
    userName: 'challgalleyg',
    email: 'mmcleseg@discovery.com',
    password: '$2a$04$vVqKmRFnhLB/Z7cYKLLmA.YFe7MqJA27Gzhma/k9EkXOa5VUjeWGa',
    isAdmin: false,
    avatar: 'https://robohash.org/rerumearumnihil.png?size=50x50&set=set1',
    status: 'active',
    favouriteGame: 'Red Dead Redemption 2',
    wishList: 'The Legend of Zelda',
    channelURL: 'https://www.youtube.com/channel/-PO-_-_1-W_',
    joinedAffiliation: false,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb0750d' },
    userName: 'cblazhevichj',
    email: 'alormanj@storify.com',
    password: '$2a$04$Fs7TRkboOfrT8ooM./ALK.qr0uMgnKiNMwZJwTESVp3FvY1ZWciKa',
    isAdmin: false,
    avatar: 'https://robohash.org/repudiandaemolestiaevel.png?size=50x50&set=set1',
    status: 'active',
    favouriteGame: 'FIFA 21',
    wishList: 'The Legend of Zelda',
    channelURL: 'https://www.youtube.com/channel/-98_-_2-an_',
    joinedAffiliation: false,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb0750e' },
    userName: 'dcleyburnk',
    email: 'vdaubneyk@histats.com',
    password: '$2a$04$KyadSvC2Pfisnfagh3cE3Os7fz5qy5w7nO.4owQsKn9Vvgutq5c1u',
    isAdmin: false,
    avatar: 'https://robohash.org/quietmolestiae.png?size=50x50&set=set1',
    status: 'active',
    favouriteGame: 'Super Mario Bros.',
    wishList: 'Minecraft',
    channelURL: 'https://www.youtube.com/channel/__6__2qOxxz',
    joinedAffiliation: true,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb0750b' },
    userName: 'divanyushinh',
    email: 'imackayh@angelfire.com',
    password: '$2a$04$1kOCw.qWCwwyVu9hAcItk.77fc5idbbcPR.ZR/ILBdrZYJMC7B4O6',
    isAdmin: false,
    avatar: 'https://robohash.org/iustoeaquia.png?size=50x50&set=set1',
    status: 'active',
    favouriteGame: 'Overwatch',
    wishList: 'FIFA 21',
    channelURL: 'http://www.youtube.com/channel/--9_-Ir0fUB',
    joinedAffiliation: false,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb0750c' },
    userName: 'vdeami',
    email: 'hlomasneyi@vimeo.com',
    password: '$2a$04$zRg7GYtzG5rDtYR4ktGTWu6aotJhShUFC6DuK7c/VtrcV4B0hZWA2',
    isAdmin: false,
    avatar: 'https://robohash.org/inventorequamearum.png?size=50x50&set=set1',
    status: 'active',
    favouriteGame: 'Super Mario Bros.',
    wishList: 'FIFA 21',
    channelURL: 'http://www.youtube.com/channel/5-3V_EFk8_c',
    joinedAffiliation: false,
    __v: { $numberInt: '0' },
  },
  {
    _id: { $oid: '648fb8ce2a35a03f1bb0750f' },
    userName: 'dmaffullil',
    email: 'eduttonl@tumblr.com',
    password: '$2a$04$5IH/sIZbfmiYedFMilugnuyV1Lyw69YIZLViJS4J.fbX38c6k5LQy',
    isAdmin: false,
    avatar: 'https://robohash.org/minimaetdolore.png?size=50x50&set=set1',
    status: 'active',
    favouriteGame: 'Minecraft',
    wishList: 'Overwatch',
    channelURL: 'https://www.youtube.com/channel/__D-__5B5_k',
    joinedAffiliation: false,
    __v: { $numberInt: '0' },
  },
];
